
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *         Do not modify: ANY CHANGES WILL GET DISCARED              *
 *********************************************************************/

module.exports = {
  pluginName: ["ttsAndroid","asrAndroid"],
  plugins: {
    ttsAndroid: {
      pluginName: "ttsAndroid",
      speechConfig: [
        /** OPTIONAL
         * a specific voice for TTS
         * @type string
         */
        "voice",
        /** OPTIONAL
         * the language/country for TTS
         * @type string
         */
        "language"
      ]
    },
    asrAndroid: {
      pluginName: "asrAndroid"
    }
  }
};
