
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *        Do not modify: ANY CHANGES WILL GET DISCARDED              *
 *********************************************************************/

var _id = "mmir-plugin-speech-android";
var _paths = {
  "mmir-plugin-speech-android/androidasr": "www/androidasr.js",
  "mmir-plugin-speech-android/androidcapabilities": "www/androidcapabilities.js",
  "mmir-plugin-speech-android/androidtts": "www/androidtts.js",
  "mmir-plugin-speech-android/asrAndroid": "www/asrAndroid.js",
  "mmir-plugin-speech-android/ttsAndroid": "www/ttsAndroid.js",
  "mmir-plugin-speech-android/asrAndroidCompat": "www/alt/asrAndroidCompat.js",
  "mmir-plugin-speech-android/asrAndroidWebpack": "www/alt/asrAndroidWebpack.js",
  "mmir-plugin-speech-android/ttsAndroidCompat": "www/alt/ttsAndroidCompat.js",
  "mmir-plugin-speech-android/ttsAndroidWebpack": "www/alt/ttsAndroidWebpack.js",
  "mmir-plugin-speech-android/androidasr_stub": "www/alt/stub/androidasr_stub.js",
  "mmir-plugin-speech-android/androidcapabilities_stub": "www/alt/stub/androidcapabilities_stub.js",
  "mmir-plugin-speech-android/androidtts_stub": "www/alt/stub/androidtts_stub.js",
  "mmir-plugin-speech-android": "www/asrAndroid.js"
};
var _workers = [];
var _exportedModules = [
  "mmir-plugin-speech-android",
  "mmir-plugin-speech-android/ttsAndroid"
];
var _dependencies = [];
var _exportedFiles = [];
var _modes = {};
var _buildConfig;
function _join(source, target, dict){
  source.forEach(function(item){
    if(!dict[item]){
      dict[item] = true;
      target.push(item);
    }
  });
};
function _getAll(type, mode, isResolve){

  if(typeof mode === 'boolean'){
    isResolve = mode;
    mode = void(0);
  }

  var data = this[type];
  var isArray = Array.isArray(data);
  var result = isArray? [] : Object.assign({}, data);
  var dupl = result;
  var mod = mode && this.modes[mode];
  if(isArray){
    dupl = {};
    if(mod && mod[type]){
      _join(this.modes[mode][type], result, dupl);
    }
    _join(data, result, dupl);
  } else if(isResolve){
    var root = __dirname;
    Object.keys(result).forEach(function(field){
      var val = result[field];
      if(mod && mod[field]){
        val = _paths[mod[field]];
      }
      result[field] = root + '/' + val;
    });
  }
  this.dependencies.forEach(function(dep){
    var depExports = require(dep + '/module-ids.gen.js');
    var depData = depExports.getAll(type, mode, isResolve);
    if(isArray){
      _join(depData, result, dupl);
    } else {
      Object.assign(result, depData)
    }
  });

  return result;
};
function _getBuildConfig(buildConfigsMap){

  var buildConfigs = [];
  var dupl = buildConfigsMap | {};
  if(_buildConfig){
    var buildConfig = require(__dirname+'/'+_buildConfig);
    if(Array.isArray(buildConfig)){
      _join(buildConfig, buildConfigs, dupl);
    } else if(!dupl){
      dupl[buildConfig] = true;
      buildConfigs.push(buildConfig);
    }
  }

  this.dependencies.forEach(function(dep){
    var depExports = require(dep + '/module-ids.gen.js');
    if(depExports.buildConfig){
      var depBuildConfigs = depExports.getBuildConfig(dupl);
      _join(depBuildConfigs, buildConfigs, dupl);
    }
  });

  return buildConfigs;
};
module.exports = {id: _id, paths: _paths, workers: _workers, modules: _exportedModules, files: _exportedFiles, dependencies: _dependencies, modes: _modes, buildConfig: _buildConfig, getAll: _getAll, getBuildConfig: _getBuildConfig};
